apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: NAMESPACE
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "microservices-ip"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/poem
        pathType: Prefix
        backend:
          service:
            name: poem-service
            port:
              number: 8000
      - path: /api/quote
        pathType: Prefix
        backend:
          service:
            name: quote-service
            port:
              number: 8001

