apiVersion: v1
kind: Secret
metadata:
  name: poem-secrets
  namespace: NAMESPACE
type: Opaque
stringData:
  API_SECRET_KEY: "PLACEHOLDER"
  ADMIN_TOKEN: "PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: quote-secrets
  namespace: NAMESPACE
type: Opaque
stringData:
  API_SECRET_KEY: "PLACEHOLDER"
  ADMIN_TOKEN: "PLACEHOLDER"

