apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: microservices-prd
    app.kubernetes.io/environment: prd
spec:
  project: default
  source:
    repoURL: https://github.com/sajjadkhan12/complete-devops-cicd.git
    targetRevision: main
    path: k8s/overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-prd
  syncPolicy:
    # Manual sync for production - requires approval
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10

