apiVersion: v1
kind: ConfigMap
metadata:
  name: poem-config
  namespace: microservices
data:
  SERVICE_NAME: "Poem Microservice"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quote-config
  namespace: microservices
data:
  SERVICE_NAME: "Quote Microservice"

