apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - namespace.yaml
  - configmap.yaml
  - poem-deployment.yaml
  - quote-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: microservices

images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/microservice-registery/poem-service
    newName: us-central1-docker.pkg.dev/PROJECT_ID/microservice-registery/poem-service
    newTag: latest
  - name: us-central1-docker.pkg.dev/PROJECT_ID/microservice-registery/quote-service
    newName: us-central1-docker.pkg.dev/PROJECT_ID/microservice-registery/quote-service
    newTag: latest
  - name: us-central1-docker.pkg.dev/PROJECT_ID/microservice-registery/frontend
    newName: us-central1-docker.pkg.dev/PROJECT_ID/microservice-registery/frontend
    newTag: latest

